// Code generated by MockGen. DO NOT EDIT.
// Source: app/services/rate_limiter_service.go
//
// Generated by this command:
//
//	mockgen -source=app/services/rate_limiter_service.go -destination=app/mocks/mock_services/rate_limiter_service.go -package=mock_services
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRateLimiterService is a mock of RateLimiterService interface.
type MockRateLimiterService struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterServiceMockRecorder
}

// MockRateLimiterServiceMockRecorder is the mock recorder for MockRateLimiterService.
type MockRateLimiterServiceMockRecorder struct {
	mock *MockRateLimiterService
}

// NewMockRateLimiterService creates a new mock instance.
func NewMockRateLimiterService(ctrl *gomock.Controller) *MockRateLimiterService {
	mock := &MockRateLimiterService{ctrl: ctrl}
	mock.recorder = &MockRateLimiterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiterService) EXPECT() *MockRateLimiterServiceMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiterService) Allow(clientIp string) (bool, time.Duration) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", clientIp)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(time.Duration)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterServiceMockRecorder) Allow(clientIp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiterService)(nil).Allow), clientIp)
}
