// Code generated by MockGen. DO NOT EDIT.
// Source: app/services/show_service.go
//
// Generated by this command:
//
//	mockgen -source=app/services/show_service.go -destination=app/mocks/mock_services/show_service.go -package=mock_services
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	errors "github.com/vantutran2k1-movie-reservation-system/reservation-service/app/errors"
	models "github.com/vantutran2k1-movie-reservation-system/reservation-service/app/models"
	payloads "github.com/vantutran2k1-movie-reservation-system/reservation-service/app/payloads"
	gomock "go.uber.org/mock/gomock"
)

// MockShowService is a mock of ShowService interface.
type MockShowService struct {
	ctrl     *gomock.Controller
	recorder *MockShowServiceMockRecorder
}

// MockShowServiceMockRecorder is the mock recorder for MockShowService.
type MockShowServiceMockRecorder struct {
	mock *MockShowService
}

// NewMockShowService creates a new mock instance.
func NewMockShowService(ctrl *gomock.Controller) *MockShowService {
	mock := &MockShowService{ctrl: ctrl}
	mock.recorder = &MockShowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowService) EXPECT() *MockShowServiceMockRecorder {
	return m.recorder
}

// CreateShow mocks base method.
func (m *MockShowService) CreateShow(req payloads.CreateShowRequest) (*models.Show, *errors.ApiError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShow", req)
	ret0, _ := ret[0].(*models.Show)
	ret1, _ := ret[1].(*errors.ApiError)
	return ret0, ret1
}

// CreateShow indicates an expected call of CreateShow.
func (mr *MockShowServiceMockRecorder) CreateShow(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShow", reflect.TypeOf((*MockShowService)(nil).CreateShow), req)
}
