services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-booking}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"

  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DATABASE=${REDIS_DATABASE:-0}

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT:-9000}:${MINIO_PORT:-9000}"
      - "${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/var/lib/minio/data
    command: server /var/lib/minio/data --console-address ":${MINIO_CONSOLE_PORT:-9001}"

volumes:
  postgres_data:
  redis_data:
  minio_data:
