// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/password_reset_token_repository.go
//
// Generated by this command:
//
//	mockgen -source=app/repositories/password_reset_token_repository.go -destination=app/mocks/mock_repositories/password_reset_token_repository.go -package=mock_repositories
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	reflect "reflect"

	models "github.com/vantutran2k1-movie-reservation-system/reservation-service/app/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPasswordResetTokenRepository is a mock of PasswordResetTokenRepository interface.
type MockPasswordResetTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetTokenRepositoryMockRecorder
}

// MockPasswordResetTokenRepositoryMockRecorder is the mock recorder for MockPasswordResetTokenRepository.
type MockPasswordResetTokenRepositoryMockRecorder struct {
	mock *MockPasswordResetTokenRepository
}

// NewMockPasswordResetTokenRepository creates a new mock instance.
func NewMockPasswordResetTokenRepository(ctrl *gomock.Controller) *MockPasswordResetTokenRepository {
	mock := &MockPasswordResetTokenRepository{ctrl: ctrl}
	mock.recorder = &MockPasswordResetTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetTokenRepository) EXPECT() *MockPasswordResetTokenRepositoryMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockPasswordResetTokenRepository) CreateToken(tx *gorm.DB, token *models.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", tx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) CreateToken(tx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).CreateToken), tx, token)
}

// GetActivePasswordResetToken mocks base method.
func (m *MockPasswordResetTokenRepository) GetActivePasswordResetToken(tokenValue string) (*models.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePasswordResetToken", tokenValue)
	ret0, _ := ret[0].(*models.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivePasswordResetToken indicates an expected call of GetActivePasswordResetToken.
func (mr *MockPasswordResetTokenRepositoryMockRecorder) GetActivePasswordResetToken(tokenValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePasswordResetToken", reflect.TypeOf((*MockPasswordResetTokenRepository)(nil).GetActivePasswordResetToken), tokenValue)
}
