// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/theater_location_repository.go
//
// Generated by this command:
//
//	mockgen -source=app/repositories/theater_location_repository.go -destination=app/mocks/mock_repositories/theater_location_repository.go -package=mock_repositories
//

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	reflect "reflect"

	filters "github.com/vantutran2k1-movie-reservation-system/reservation-service/app/filters"
	models "github.com/vantutran2k1-movie-reservation-system/reservation-service/app/models"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockTheaterLocationRepository is a mock of TheaterLocationRepository interface.
type MockTheaterLocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTheaterLocationRepositoryMockRecorder
}

// MockTheaterLocationRepositoryMockRecorder is the mock recorder for MockTheaterLocationRepository.
type MockTheaterLocationRepositoryMockRecorder struct {
	mock *MockTheaterLocationRepository
}

// NewMockTheaterLocationRepository creates a new mock instance.
func NewMockTheaterLocationRepository(ctrl *gomock.Controller) *MockTheaterLocationRepository {
	mock := &MockTheaterLocationRepository{ctrl: ctrl}
	mock.recorder = &MockTheaterLocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTheaterLocationRepository) EXPECT() *MockTheaterLocationRepositoryMockRecorder {
	return m.recorder
}

// CreateTheaterLocation mocks base method.
func (m *MockTheaterLocationRepository) CreateTheaterLocation(tx *gorm.DB, location *models.TheaterLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTheaterLocation", tx, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTheaterLocation indicates an expected call of CreateTheaterLocation.
func (mr *MockTheaterLocationRepositoryMockRecorder) CreateTheaterLocation(tx, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTheaterLocation", reflect.TypeOf((*MockTheaterLocationRepository)(nil).CreateTheaterLocation), tx, location)
}

// GetLocation mocks base method.
func (m *MockTheaterLocationRepository) GetLocation(filter filters.TheaterLocationFilter) (*models.TheaterLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocation", filter)
	ret0, _ := ret[0].(*models.TheaterLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocation indicates an expected call of GetLocation.
func (mr *MockTheaterLocationRepositoryMockRecorder) GetLocation(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocation", reflect.TypeOf((*MockTheaterLocationRepository)(nil).GetLocation), filter)
}

// UpdateTheaterLocation mocks base method.
func (m *MockTheaterLocationRepository) UpdateTheaterLocation(tx *gorm.DB, location *models.TheaterLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTheaterLocation", tx, location)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTheaterLocation indicates an expected call of UpdateTheaterLocation.
func (mr *MockTheaterLocationRepositoryMockRecorder) UpdateTheaterLocation(tx, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTheaterLocation", reflect.TypeOf((*MockTheaterLocationRepository)(nil).UpdateTheaterLocation), tx, location)
}
